quarkus:
  level: INFO
  langchain4j:
    neo4j:
      dimension: 768
    ollama:
      base-url: http://localhost:11434/
      timeout: 3000s
      chat-model:
        model-id: gpt-oss
      embedding-model:
        model-id: nomic-embed-text

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: test1234

  oidc:
    auth-server-url: http://localhost:8088/realms/find-dog-ia
    application-type: service
    client-id: find-dog-client-id
    credentials:
      secret: LHJe20fo3Nx4y0SwoXD8sqbAeSkFAVKH
    roles:
      role-claim-path: realm_access/roles
      role-claim-separator: " "

  http:
    auth:
      permission:
        public:
          paths: /hello
          policy: permit
        secured:
          paths: /*
          policy: authenticated